/*Generated at: 1607591710, Cache ends at: 1607627710,en_US*/

/**
 * Copyright (c) 2019-present, PL Productions LLC. All rights reserved.
 *
 * You are hereby granted a non-exclusive, worldwide, royalty-free license to use,
 * copy, modify, and distribute this software in source code or binary form for use
 * in connection with the web services and APIs provided by VersatileNode.
 *
 * As with any software that integrates with the VersatileNode platform, your use of
 * this software is subject to the VersatileNode Platform Policy
 * [https://versatilenode.com/tos.html]. This copyright notice shall be
 * included in all copies or substantial portions of the software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
 * FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
 * IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
**/
/** We use CryptoJS in our code, so we'll include their licence as required. */
/**
# License

[The MIT License (MIT)](http://opensource.org/licenses/MIT)

Copyright (c) 2009-2013 Jeff Mott  
Copyright (c) 2013-2016 Evan Vosberg

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/

function formatErrorMessage(jqXHR,exception){if(jqXHR.status===0){return('Not connected.\nPlease verify your network connection.');}else if(jqXHR.status==404){return('The requested page not found. [404]');}else if(jqXHR.status==500){return('Internal Server Error [500].');}else if(exception==='parsererror'){return('Requested JSON parse failed.');}else if(exception==='timeout'){return('Time out error.');}else if(exception==='abort'){return('Ajax request aborted.');}else{return('Uncaught Error.\n'+jqXHR.responseText);}}
jQuery.postCORSX=function(url,at='',data,func){if(func==undefined)func=function(){};return $.ajax({type:'POST',url:url,data:data,dataType:'json',contentType:'application/x-www-form-urlencoded',xhrFields:{withCredentials:true},success:function(res){func(res)},error:function(){jQuery('#accthistoryinfo').html('There was an error loading your history.');func({})}});}
jQuery.getCORSX=function(url,at='',data,func){if(func==undefined)func=function(){};if(at!='')
{return $.ajax({type:'GET',url:url,data:data,dataType:'json',contentType:'application/x-www-form-urlencoded',xhrFields:{withCredentials:true},beforeSend:function(xhr){xhr.setRequestHeader('Authorization','Bearer '+at);},success:function(res){func(res)},error:function(request,status,error){jQuery('#accthistoryinfo').html('There was an error loading your history:<br/>'+formatErrorMessage(request,error));func({})}});}
else
{return $.ajax({type:'GET',url:url,data:data,dataType:'json',contentType:'application/x-www-form-urlencoded',xhrFields:{withCredentials:true},success:function(res){func(res)},error:function(request,status,error){jQuery('#accthistoryinfo').html('There was an error loading your history:<br/>'+formatErrorMessage(request,error));func({})}});}}
sunsx=function(type){switch(type){case'access_token':return'Access Token granted to';break;case'granted_by_user':return'You logged in to';break;default:return'NaN';break;}}
faBrowser=function(t){if(null==t)
return'<span title="Unknown Browser"><i class="far fa-question-circle google-plus"></i></span>';var e;switch(t){case'Playstation Browser':e='<span title="'+t+'"><i class="fab fa-playstation playstation"></i></span>';break;case"Opera":case"Opera GX":e='<span title="'+t+'"><i class="fab fa-opera opera"></i></span>';break;case"Microsoft Edge":case"Edge":e='<span title="'+t+'"><i class="fab fa-edge edge"></i></span>';break;case"Safari":case"Apple Safari":e='<span title="'+t+'"><i class="fab fa-safari safari"></i></span>';break;case"Firefox":case"Mozilla Firefox":e='<span title="'+t+'"><i class="fab fa-firefox firefox"></i></span>';break;case"Google Chrome":case"Chromium":case"Brave":e='<span title="'+t+'"><i class="fab fa-chrome chrome"></i></span>';break;default:e='<span title="'+t+'"><i class="far fa-question-circle google-plus"></i></span>'}
return e}
faOS=function(t){if(null==t)
return'<span title="Unknown OS"><i class="far fa-question-circle google-plus"></i></span>';var e;switch(t){case'Linux':e='<span title="'+t+'"><i class="fab fa-linux linux"></i></span>';break;case'Playstation Vita':case'PS Vita':case'Playstation 3':case'Playstation 4':e='<span title="'+t+'"><i class="fab fa-playstation playstation"></i></span>';break;case"Chrome OS":e='<span title="'+t+'"><i class="fab fa-google google"></i><i class="fab fa-chrome chrome"></i></span>';break;case"Android":e='<span title="'+t+'"><i class="fab fa-android android"></i></span>';break;case"Mac OS X":case"iPhone":case"iPod Touch":case"iPad":case"Mac":e='<span title="'+t+'"><i class="fab fa-apple apple"></i></span>';break;case"Windows 7":case"Windows 10":case"Windows XP":case"Windows Vista":case"Windows 8":case"Windows 8.1":e='<span title="'+t+'"><i class="fab fa-windows windows"></i></span>';break;default:e='<span title="'+t+'"><i class="far fa-question-circle google-plus"></i></span>'}
return e}
jQuery('#accthistoryinfo').html('Loading your login history.');window.billing_accessToken='';billing_access_generate=function(){jQuery.getCORSX('https://graph.versatilenode.com/id/openid/billing/authorize/','','',function(json){window.billing_accessToken=json.token;});}
billing_access_generate();acctRefreshX=function(){jQuery.getCORSX('https://v2.graph.versatilenode.com/me/account/history/',billing_accessToken,'',function(ca){var historykeys={incorrect_password:0,successful:0};var ximn='<ul class="timeline">';jQuery.each(ca.data,function(key,index){if(index.sign_in.signed_in=='1'&&index.reason!==''&&index.is_app=='1')
{ximn=ximn+'<li class="success"><p class="text-light m-b-0"><strong class="twofa-config-link disable" data-i18n="success">Signed in to '+index.reason+'</strong> using <strong>'+index.browser+'</strong> '+faBrowser(index.browser)+' on <strong>'+index.device+'</strong> '+faOS(index.device)+'&nbsp;&nbsp;&nbsp;<span alt="'+index.geolocation.country+'" title="'+index.geolocation.country+'" class="flag-icon flag-icon-'+flagReady(index.geolocation.country_code)+'"></span> <a href="#" class="float-right"><time datetime="'+index.timestamp+'" class="timeago"></time></a></p></li>';}
else if(index.sign_in.activated_ban=='1')
{ximn=ximn+'<li class="error"><p class="text-light m-b-0"><strong class="twofa-config-link disable" data-i18n="temp-locked">Temporarily locked</strong> using <strong>'+index.browser+'</strong> '+faBrowser(index.browser)+' on <strong>'+index.device+'</strong> '+faOS(index.device)+'&nbsp;&nbsp;&nbsp;<span alt="'+index.geolocation.country+'" title="'+index.geolocation.country+'" class="flag-icon flag-icon-'+flagReady(index.geolocation.country_code)+'"></span> <a href="#" class="float-right"><time datetime="'+index.timestamp+'" class="timeago"></time></a> &mdash; <a href="https://accounts.versatilenode.com/id/logout/?wreply=https://billing.versatilenode.com/password/reset/begin">Change password</a></p></li>';}
else if(index.sign_in.incorrect_password=='1')
{ximn=ximn+'<li class="error"><p class="text-light m-b-0"><strong class="twofa-config-link disable" data-i18n="password-incorrect">Password incorrect</strong> using <strong>'+index.browser+'</strong> '+faBrowser(index.browser)+' on <strong>'+index.device+'</strong> '+faOS(index.device)+'&nbsp;&nbsp;&nbsp;<span alt="'+index.geolocation.country+'" title="'+index.geolocation.country+'" class="flag-icon flag-icon-'+flagReady(index.geolocation.country_code)+'"></span> <a href="#" class="float-right"><time datetime="'+index.timestamp+'" class="timeago"></time></a> &mdash; <a href="https://accounts.versatilenode.com/id/logout/?wreply=https://billing.versatilenode.com/password/reset/begin">Change password</a></p></li>';historykeys.incorrect_password++;}
else if(index.sign_in.signed_in=='1'&&index.sign_in.successful=='1')
{ximn=ximn+'<li class="success"><p class="text-light m-b-0"><strong class="twofa-config-link disable" data-i18n="success">Sign in successful</strong> using <strong>'+index.browser+'</strong> '+faBrowser(index.browser)+' on <strong>'+index.device+'</strong> '+faOS(index.device)+'&nbsp;&nbsp;&nbsp;<span alt="'+index.geolocation.country+'" title="'+index.geolocation.country+'" class="flag-icon flag-icon-'+flagReady(index.geolocation.country_code)+'"></span> <a href="#" class="float-right"><time datetime="'+index.timestamp+'" class="timeago"></time></a></p></li>';}
else if(index.otp.requested=='0'&&index.otp.verified=='1'&&index.sign_in.signed_in=='1'&&index.sign_in.successful=='1')
{ximn=ximn+'<li class="success"><p class="text-light m-b-0"><strong class="twofa-config-link disable" data-i18n="success">2nd Factor verified</strong> using <strong>'+index.browser+'</strong> '+faBrowser(index.browser)+' on <strong>'+index.device+'</strong> '+faOS(index.device)+'&nbsp;&nbsp;&nbsp;<span alt="'+index.geolocation.country+'" title="'+index.geolocation.country+'" class="flag-icon flag-icon-'+flagReady(index.geolocation.country_code)+'"></span> <a href="#" class="float-right"><time datetime="'+index.timestamp+'" class="timeago"></time></a></p></li>';}
else if(index.otp.requested=='0'&&index.otp.verified=='1')
{ximn=ximn+'<li><p class="text-light m-b-0"><strong class="twofa-config-link disable" data-i18n="otp-verified">2nd Factor verified</strong> using <strong>'+index.browser+'</strong> '+faBrowser(index.browser)+' on <strong>'+index.device+'</strong> '+faOS(index.device)+'&nbsp;&nbsp;&nbsp;<span alt="'+index.geolocation.country+'" title="'+index.geolocation.country+'" class="flag-icon flag-icon-'+flagReady(index.geolocation.country_code)+'"></span> <a href="#" class="float-right"><time datetime="'+index.timestamp+'" class="timeago"></time></a></p></li>';}
else if(index.otp.requested=='1')
{ximn=ximn+'<li><p class="text-light m-b-0"><strong class="twofa-config-link disable" data-i18n="otp-requested">2nd Factor requested</strong> using <strong>'+index.browser+'</strong> '+faBrowser(index.browser)+' on <strong>'+index.device+'</strong> '+faOS(index.device)+'&nbsp;&nbsp;&nbsp;<span alt="'+index.geolocation.country+'" title="'+index.geolocation.country+'" class="flag-icon flag-icon-'+flagReady(index.geolocation.country_code)+'"></span> <a href="#" class="float-right"><time datetime="'+index.timestamp+'" class="timeago"></time></a></p></li>';}
else
{ximn=ximn+'<li><p class="text-light m-b-0"><strong data-i18n="arcsacana">Account ready for password</strong> using <strong>'+index.browser+'</strong> '+faBrowser(index.browser)+' on <strong>'+index.device+'</strong> '+faOS(index.device)+'&nbsp;&nbsp;&nbsp;<span alt="'+index.geolocation.country+'" title="'+index.geolocation.country+'" class="flag-icon flag-icon-'+flagReady(index.geolocation.country_code)+'"></span> <a href="#" class="float-right"><time datetime="'+index.timestamp+'" class="timeago"></time></a></p></li>';};});jQuery('#accthistoryloader').slideUp();jQuery('#xins').html(ximn+'</ul>');jQuery("time.timeago").timeago();jQuery('#accthistory').slideDown();});}
acctRefresh=function(){jQuery.getCORSX('https://v2.graph.versatilenode.com/me/account/history/',billing_accessToken,'',function(ca){var historykeys={incorrect_password:0,successful:0};var ximn='<ul class="timeline">';jQuery.each(ca.data,function(key,index){if(index.sign_in.signed_in=='1'&&index.reason!==''&&index.is_app=='1')
{ximn=ximn+'<li class="success"><p class="text-light m-b-0"><strong class="twofa-config-link disable" data-i18n="success">Signed in to '+index.reason+'</strong> using <strong>'+index.browser+'</strong> '+faBrowser(index.browser)+' on <strong>'+index.device+'</strong> '+faOS(index.device)+'&nbsp;&nbsp;&nbsp;<span alt="'+index.geolocation.country+'" title="'+index.geolocation.country+'" class="flag-icon flag-icon-'+flagReady(index.geolocation.country_code)+'"></span> <a href="#" class="float-right"><time datetime="'+index.timestamp+'" class="timeago"></time></a></p></li>';}
else if(index.sign_in.activated_ban=='1')
{ximn=ximn+'<li class="error"><p class="text-light m-b-0"><strong class="twofa-config-link disable" data-i18n="temp-locked">Temporarily locked</strong> using <strong>'+index.browser+'</strong> '+faBrowser(index.browser)+' on <strong>'+index.device+'</strong> '+faOS(index.device)+'&nbsp;&nbsp;&nbsp;<span alt="'+index.geolocation.country+'" title="'+index.geolocation.country+'" class="flag-icon flag-icon-'+flagReady(index.geolocation.country_code)+'"></span> <a href="#" class="float-right"><time datetime="'+index.timestamp+'" class="timeago"></time></a> &mdash; <a href="https://accounts.versatilenode.com/id/logout/?wreply=https://billing.versatilenode.com/password/reset/begin">Change password</a></p></li>';}
else if(index.sign_in.incorrect_password=='1')
{ximn=ximn+'<li class="error"><p class="text-light m-b-0"><strong class="twofa-config-link disable" data-i18n="password-incorrect">Password incorrect</strong> using <strong>'+index.browser+'</strong> '+faBrowser(index.browser)+' on <strong>'+index.device+'</strong> '+faOS(index.device)+'&nbsp;&nbsp;&nbsp;<span alt="'+index.geolocation.country+'" title="'+index.geolocation.country+'" class="flag-icon flag-icon-'+flagReady(index.geolocation.country_code)+'"></span> <a href="#" class="float-right"><time datetime="'+index.timestamp+'" class="timeago"></time></a> &mdash; <a href="https://accounts.versatilenode.com/id/logout/?wreply=https://billing.versatilenode.com/password/reset/begin">Change password</a></p></li>';historykeys.incorrect_password++;}
else if(index.sign_in.signed_in=='1'&&index.sign_in.successful=='1')
{ximn=ximn+'<li class="success"><p class="text-light m-b-0"><strong class="twofa-config-link disable" data-i18n="success">Sign in successful</strong> using <strong>'+index.browser+'</strong> '+faBrowser(index.browser)+' on <strong>'+index.device+'</strong> '+faOS(index.device)+'&nbsp;&nbsp;&nbsp;<span alt="'+index.geolocation.country+'" title="'+index.geolocation.country+'" class="flag-icon flag-icon-'+flagReady(index.geolocation.country_code)+'"></span> <a href="#" class="float-right"><time datetime="'+index.timestamp+'" class="timeago"></time></a></p></li>';}
else if(index.otp.requested=='0'&&index.otp.verified=='1'&&index.sign_in.signed_in=='1'&&index.sign_in.successful=='1')
{ximn=ximn+'<li class="success"><p class="text-light m-b-0"><strong class="twofa-config-link disable" data-i18n="success">2nd Factor verified</strong> using <strong>'+index.browser+'</strong> '+faBrowser(index.browser)+' on <strong>'+index.device+'</strong> '+faOS(index.device)+'&nbsp;&nbsp;&nbsp;<span alt="'+index.geolocation.country+'" title="'+index.geolocation.country+'" class="flag-icon flag-icon-'+flagReady(index.geolocation.country_code)+'"></span> <a href="#" class="float-right"><time datetime="'+index.timestamp+'" class="timeago"></time></a></p></li>';}
else if(index.otp.requested=='0'&&index.otp.verified=='1')
{ximn=ximn+'<li><p class="text-light m-b-0"><strong class="twofa-config-link disable" data-i18n="otp-verified">2nd Factor verified</strong> using <strong>'+index.browser+'</strong> '+faBrowser(index.browser)+' on <strong>'+index.device+'</strong> '+faOS(index.device)+'&nbsp;&nbsp;&nbsp;<span alt="'+index.geolocation.country+'" title="'+index.geolocation.country+'" class="flag-icon flag-icon-'+flagReady(index.geolocation.country_code)+'"></span> <a href="#" class="float-right"><time datetime="'+index.timestamp+'" class="timeago"></time></a></p></li>';}
else if(index.otp.requested=='1')
{ximn=ximn+'<li><p class="text-light m-b-0"><strong class="twofa-config-link disable" data-i18n="otp-requested">2nd Factor requested</strong> using <strong>'+index.browser+'</strong> '+faBrowser(index.browser)+' on <strong>'+index.device+'</strong> '+faOS(index.device)+'&nbsp;&nbsp;&nbsp;<span alt="'+index.geolocation.country+'" title="'+index.geolocation.country+'" class="flag-icon flag-icon-'+flagReady(index.geolocation.country_code)+'"></span> <a href="#" class="float-right"><time datetime="'+index.timestamp+'" class="timeago"></time></a></p></li>';}
else
{ximn=ximn+'<li><p class="text-light m-b-0"><strong data-i18n="arcsacana">Account ready for password</strong> using <strong>'+index.browser+'</strong> '+faBrowser(index.browser)+' on <strong>'+index.device+'</strong> '+faOS(index.device)+'&nbsp;&nbsp;&nbsp;<span alt="'+index.geolocation.country+'" title="'+index.geolocation.country+'" class="flag-icon flag-icon-'+flagReady(index.geolocation.country_code)+'"></span> <a href="#" class="float-right"><time datetime="'+index.timestamp+'" class="timeago"></time></a></p></li>';};});jQuery('#accthistoryloader').slideUp();jQuery('#xins').html(ximn+'</ul>');jQuery("time.timeago").timeago();jQuery('#accthistory').slideDown();});}
flagReady=function(str){return str.toLowerCase();}
jQuery(document).ready(function(){jQuery('body').append('<style>.apple{color:grey!important;}ul.timeline{list-style-type:none;position:relative}ul.timeline:before{content:\' \';background:#d4d9df;display:inline-block;position:absolute;left:29px;width:2px;height:100%;z-index:400}ul.timeline>li{margin:20px 0;padding-left:20px}ul.timeline>li.success:before{content:\' \';background:#fff;display:inline-block;position:absolute;border-radius:50%;border:3px solid #68ab11;left:20px;width:20px;height:20px;z-index:400}ul.timeline>li.error:before{content:\' \';background:#fff;display:inline-block;position:absolute;border-radius:50%;border:3px solid #ab1132;left:20px;width:20px;height:20px;z-index:400}ul.timeline>li:before{content:\' \';background:#fff;display:inline-block;position:absolute;border-radius:50%;border:3px solid #22c0e8;left:20px;width:20px;height:20px;z-index:400}.spinner>div{background:#fbb03b!important}.fa-chrome{background:linear-gradient(to bottom left,transparent 49%,#ea4335 50%) 105% 0/37% 30%,linear-gradient(to bottom right,transparent 49%,#fbbc05 50%) 64% 100%/35% 43%,radial-gradient(farthest-side,#4285f4 46%,transparent 47%),linear-gradient(47deg,#34a853 42%,transparent 43%),linear-gradient(-72deg,#fbbc05 42%,transparent 43%),linear-gradient(-199deg,#ea4335 42%,transparent 43%);background-repeat:no-repeat;color:transparent;-webkit-background-clip:text;background-clip:text}.playstation{color:#003087}</style>');setTimeout(function(){jQuery('#accthistoryinfo').html('Your account login history will be displayed here in real time.');jQuery.getCORSX('https://v2.graph.versatilenode.com/me/account/history/',billing_accessToken,'',function(ca){var historykeys={incorrect_password:0,successful:0};var ximn='<ul class="timeline">';jQuery.each(ca.data,function(key,index){if(index.sign_in.signed_in=='1'&&index.reason!==''&&index.is_app=='1')
{ximn=ximn+'<li class="success"><p class="text-light m-b-0"><strong class="twofa-config-link disable" data-i18n="success">Signed in to '+index.reason+'</strong> using <strong>'+index.browser+'</strong> '+faBrowser(index.browser)+' on <strong>'+index.device+'</strong> '+faOS(index.device)+'&nbsp;&nbsp;&nbsp;<span alt="'+index.geolocation.country+'" title="'+index.geolocation.country+'" class="flag-icon flag-icon-'+flagReady(index.geolocation.country_code)+'"></span> <a href="#" class="float-right"><time datetime="'+index.timestamp+'" class="timeago"></time></a></p></li>';}
else if(index.sign_in.activated_ban=='1')
{ximn=ximn+'<li class="error"><p class="text-light m-b-0"><strong class="twofa-config-link disable" data-i18n="temp-locked">Temporarily locked</strong> using <strong>'+index.browser+'</strong> '+faBrowser(index.browser)+' on <strong>'+index.device+'</strong> '+faOS(index.device)+'&nbsp;&nbsp;&nbsp;<span alt="'+index.geolocation.country+'" title="'+index.geolocation.country+'" class="flag-icon flag-icon-'+flagReady(index.geolocation.country_code)+'"></span> <a href="#" class="float-right"><time datetime="'+index.timestamp+'" class="timeago"></time></a> &mdash; <a href="https://accounts.versatilenode.com/id/logout/?wreply=https://billing.versatilenode.com/password/reset/begin">Change password</a></p></li>';}
else if(index.sign_in.incorrect_password=='1')
{ximn=ximn+'<li class="error"><p class="text-light m-b-0"><strong class="twofa-config-link disable" data-i18n="password-incorrect">Password incorrect</strong> using <strong>'+index.browser+'</strong> '+faBrowser(index.browser)+' on <strong>'+index.device+'</strong> '+faOS(index.device)+'&nbsp;&nbsp;&nbsp;<span alt="'+index.geolocation.country+'" title="'+index.geolocation.country+'" class="flag-icon flag-icon-'+flagReady(index.geolocation.country_code)+'"></span> <a href="#" class="float-right"><time datetime="'+index.timestamp+'" class="timeago"></time></a> &mdash; <a href="https://accounts.versatilenode.com/id/logout/?wreply=https://billing.versatilenode.com/password/reset/begin">Change password</a></p></li>';historykeys.incorrect_password++;}
else if(index.sign_in.signed_in=='1'&&index.sign_in.successful=='1')
{ximn=ximn+'<li class="success"><p class="text-light m-b-0"><strong class="twofa-config-link disable" data-i18n="success">Sign in successful</strong> using <strong>'+index.browser+'</strong> '+faBrowser(index.browser)+' on <strong>'+index.device+'</strong> '+faOS(index.device)+'&nbsp;&nbsp;&nbsp;<span alt="'+index.geolocation.country+'" title="'+index.geolocation.country+'" class="flag-icon flag-icon-'+flagReady(index.geolocation.country_code)+'"></span> <a href="#" class="float-right"><time datetime="'+index.timestamp+'" class="timeago"></time></a></p></li>';}
else if(index.otp.requested=='0'&&index.otp.verified=='1'&&index.sign_in.signed_in=='1'&&index.sign_in.successful=='1')
{ximn=ximn+'<li class="success"><p class="text-light m-b-0"><strong class="twofa-config-link disable" data-i18n="success">2nd Factor verified</strong> using <strong>'+index.browser+'</strong> '+faBrowser(index.browser)+' on <strong>'+index.device+'</strong> '+faOS(index.device)+'&nbsp;&nbsp;&nbsp;<span alt="'+index.geolocation.country+'" title="'+index.geolocation.country+'" class="flag-icon flag-icon-'+flagReady(index.geolocation.country_code)+'"></span> <a href="#" class="float-right"><time datetime="'+index.timestamp+'" class="timeago"></time></a></p></li>';}
else if(index.otp.requested=='0'&&index.otp.verified=='1')
{ximn=ximn+'<li><p class="text-light m-b-0"><strong class="twofa-config-link disable" data-i18n="otp-verified">2nd Factor verified</strong> using <strong>'+index.browser+'</strong> '+faBrowser(index.browser)+' on <strong>'+index.device+'</strong> '+faOS(index.device)+'&nbsp;&nbsp;&nbsp;<span alt="'+index.geolocation.country+'" title="'+index.geolocation.country+'" class="flag-icon flag-icon-'+flagReady(index.geolocation.country_code)+'"></span> <a href="#" class="float-right"><time datetime="'+index.timestamp+'" class="timeago"></time></a></p></li>';}
else if(index.otp.requested=='1')
{ximn=ximn+'<li><p class="text-light m-b-0"><strong class="twofa-config-link disable" data-i18n="otp-requested">2nd Factor requested</strong> using <strong>'+index.browser+'</strong> '+faBrowser(index.browser)+' on <strong>'+index.device+'</strong> '+faOS(index.device)+'&nbsp;&nbsp;&nbsp;<span alt="'+index.geolocation.country+'" title="'+index.geolocation.country+'" class="flag-icon flag-icon-'+flagReady(index.geolocation.country_code)+'"></span> <a href="#" class="float-right"><time datetime="'+index.timestamp+'" class="timeago"></time></a></p></li>';}
else
{ximn=ximn+'<li><p class="text-light m-b-0"><strong data-i18n="arcsacana">Account ready for password</strong> using <strong>'+index.browser+'</strong> '+faBrowser(index.browser)+' on <strong>'+index.device+'</strong> '+faOS(index.device)+'&nbsp;&nbsp;&nbsp;<span alt="'+index.geolocation.country+'" title="'+index.geolocation.country+'" class="flag-icon flag-icon-'+flagReady(index.geolocation.country_code)+'"></span> <a href="#" class="float-right"><time datetime="'+index.timestamp+'" class="timeago"></time></a></p></li>';};});jQuery('#accthistoryloader').slideUp();jQuery('#xins').html(ximn+'</ul>');jQuery("time.timeago").timeago();jQuery('#accthistory').slideDown();});},1000);jQuery('#acctrefresh').on('click',function(e){jQuery('#accthistoryloader').slideDown();acctRefresh();e.preventDefault();});setInterval(billing_access_generate,60*60*1000);setInterval(acctRefreshX,10000);});
/** Hashkey: b92f1bbd1ba1236837dc8f489ea4ff31e9106154d6df61cfdb7335b353b1305b **/
 
/** End of generated JS File **/
 