var windowFocus=true;var username;var chatHeartbeatCount=0;var minChatHeartbeat=1000;var maxChatHeartbeat=33000;var chatHeartbeatTime=minChatHeartbeat;var originalTitle;var blinkOrder=0;var chatboxFocus=[];var newMessages=[];var newMessagesWin=[];var chatBoxes=[];Element.prototype.remove=function(){this.parentElement.removeChild(this);};NodeList.prototype.remove=HTMLCollection.prototype.remove=function(){for(var i=this.length- 1;i>=0;i--){if(this[i]&&this[i].parentElement){this[i].parentElement.removeChild(this[i]);}}};sf.chat_app={w:window,d:document,l:document.location.href,e:encodeURIComponent,browser:function(){var check=false;(function(a){if(/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge |maemo|midp|mmp|mobile.+firefox|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows ce|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|yas\-|your|zeto|zte\-/i.test(a.substr(0,4)))check=true;})
(navigator.userAgent||navigator.vendor||window.opera);return check;},a:function(as){alert(as);},dom:function(id){return app.d.getElementById(id);},focus:function(id){return app.d.getElementById(id).focus();}};sf.chat_app.activity=0;sf.app_init=function(){if(sf.chat_app.browser()===true){sf.chat_app.activity=0;if(window.console&&console.log)
{console.log('REEEEE mobiles get out');}
else
{}}
else if(sf.user_info.id===""||document.getElementById("login-form"))
{sf.chat_app.activity=0;if(window.console&&console.log)
{console.log('Desktop environment detected, but user is guest :(');}
else
{}}
else
{sf.chat_app.activity=1;if(window.console&&console.log)
{console.log('Desktop environment detected, chat app launched! :D');}
else
{}}};sf.cookie={get:function(a){getCookie(a);},set:function(a,b,c){setCookie(a,b,c);}};sf.scrollbars='<div id="ascrail2002" class="nicescroll-rails nicescroll-rails-vr" style="padding-right: 3px; width: 7px; z-index: auto; cursor: default; position: absolute; top: 634px; left: 1511.5px; height: 400px; display: block; opacity: 0;"><div class="nicescroll-cursors" style="position: relative; top: 0px; float: right; width: 7px; height: 219px; background-color: rgb(85, 85, 85); background-clip: padding-box; border-radius: 5px;"></div></div>';sf.options='<ul class="nav nav-pills preferences">'+'<li class="dropdown">'+'<a class="dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="false"><i class="fa fa-angle-down"></i></a>'+'<ul class="dropdown-menu pull-right">'+'<li><a href="javascript:togglePanelUp(\'friends-panel\');" class="panel-collapse"><i class="fa fa-minus-square"></i> Collapse</a></li>'+'<li><a href="javascript:togglePanelDown(\'friends-panel\');" class="panel-expand" style="display:none;"><i class="fa fa-plus-square"></i> Expand</a></li>'+'</ul>'+'</li>'+'</ul>'+'<script type="text/javascript">'+'$(document).ready(function () {'+'checkPanelMenuCookie(\'friends-panel\');'+'});'+'</script>';sf.chat='<div class="panel panel-default animated bounceIn" id="friends-panel">'+'<!-- Display chat menu widget -->'+
sf.options+'<div class="panel-heading">'+'<strong>Instant</strong> messenger</div>'+'<div class="panel-body media-list activities" id="friends_body">'+'</div>'+'</div>';sf.load=function(id){var ham='';if(id!==''){ham='<div id="humhub-ui-loader-default" class="loader humhub-ui-loader" id="'+id+'_loader">'+'<div class="sk-spinner sk-spinner-three-bounce">'+'<div class="sk-bounce1"></div>'+'<div class="sk-bounce2"></div>'+'<div class="sk-bounce3"></div>'+'</div>'+'</div>';}
else
{ham='<div id="humhub-ui-loader-default" class="loader humhub-ui-loader">'+'<div class="sk-spinner sk-spinner-three-bounce">'+'<div class="sk-bounce1"></div>'+'<div class="sk-bounce2"></div>'+'<div class="sk-bounce3"></div>'+'</div>'+'</div>';}
return ham;};sf.chat_friends=function(b){var ine='';$.each(b.friends,function(a,b){if(document.getElementById('friend_id'+b.id))
{ine=ine+'<div class="media"><a id="friend_id'+b.id+'" class="chat-profile-ine-'+b.id+'" onclick="chatWith(\''+b.username+'\');" data-xid="'+b.id+'">'+'<img src="'+b.avatar+'" class="img-rounded tt img_margin" height="32" width="32" alt="32x32" data-src="holder.js/32x32" style="width: 32px; height: 32px; opacity: 1; display: inline;" title="'+b.name+'">&nbsp;&nbsp;<strong>'+b.name+'</strong>'+'</a></div>';}
else
{ine=ine+'<div class="media"><a id="friend_id'+b.id+'" class="chat-profile-ine-'+b.id+'" onclick="chatWith(\''+b.username+'\');" data-xid="'+b.id+'">'+'<img src="'+b.avatar+'" class="img-rounded tt img_margin" height="32" width="32" alt="32x32" data-src="holder.js/32x32" style="width: 32px; height: 32px; opacity: 1; display: inline;" title="'+b.name+'">&nbsp;&nbsp;<strong>'+b.name+'</strong>'+'</a></div>';}});$('#friends_body').html(ine);};window.prepareFarea=function(){if(document.getElementById('friends_body'))
{}
else if(!$('div').hasClass('panel-activities'))
{}
else
{$('.panel-activities').before(sf.chat);$('#friends_body').html(sf.load());doFriends();};}
window.doFriends=function(){$.ajax({url:"https://"+sf.pull_host+"/ajax/pull/friends?token="+sf.token(),cache:false,dataType:"json",xhrFields:{withCredentials:true},success:function(data){sf.chat_friends(data);},error:function(jh){}});}
window.goToProfile=function(name){$('#layout-content').slideUp('fast',function(){$('#layout-content').html(sf.load());});$('#layout-content').slideDown('fast',function(){$.getJSON('https://'+sf.pull_host+'/ajax/pull/profile?token='+sf.token(),{'action':'q','username':name},function(a){$('body').append('<a href=\'https://www.starfuckers.org/u/'+a.username+'/?_ref=chatbar\' id=\'click_'+a.id+'\' style=\'display:none;visibility:hidden;\'></a>');$('#click_'+a.id).click();});});toggleChatBoxGrowth(name);return false;}
window.restructureChatBoxes=function(){align=0;for(x in chatBoxes){chatboxtitle=chatBoxes[x];if($("#chatbox_"+chatboxtitle).css('display')!='none'){if(align==0){$("#chatbox_"+chatboxtitle).css('right','20px');}else{width=(align)*(225+7)+20;$("#chatbox_"+chatboxtitle).css('right',width+'px');}
align++;}}}
window.chatWith=function(chatuser){createChatBox(chatuser);$("#chatbox_"+chatuser+" .chatboxtextarea").focus();}
window.createChatBox=function(chatboxtitle,minimizeChatBox){if($("#chatbox_"+chatboxtitle).length>0){if($("#chatbox_"+chatboxtitle).css('display')=='none'){$("#chatbox_"+chatboxtitle).css('display','block');restructureChatBoxes();}
$("#chatbox_"+chatboxtitle+" .chatboxtextarea").focus();return;}
$(" <div />").attr("id","chatbox_"+chatboxtitle).addClass("chatbox").html('<div class="chatboxhead" onclick="javascript:toggleChatBoxGrowth(\''+chatboxtitle+'\')" style="cursor: pointer;"><div id="title_'+chatboxtitle+'"class="chatboxtitle çhatboxhover" onclick="goToProfile(\''+chatboxtitle+'\'); return false;">'+chatboxtitle+'</div><div class="chatboxoptions"> <a href="javascript:void(0)" onclick="javascript:closeChatBox(\''+chatboxtitle+'\')">X</a></div><br clear="all"/></div><div class="chatboxcontent">'+sf.load(chatboxtitle)+'</div><div class="chatboxinput"><textarea class="chatboxtextarea" onkeydown="javascript:return checkChatBoxInputKey(event,this,\''+chatboxtitle+'\');"></textarea></div>').appendTo($("body"));setTimeout(function(){$('#chatbox_'+chatboxtitle+' div .humhub-ui-loader').slideUp();},1000);$("#chatbox_"+chatboxtitle).css('bottom','0px');chatBoxeslength=0;for(x in chatBoxes){if($("#chatbox_"+chatBoxes[x]).css('display')!='none'){chatBoxeslength++;}}
if(chatBoxeslength==0){$("#chatbox_"+chatboxtitle).css('right','20px');}else{width=(chatBoxeslength)*(225+7)+20;$("#chatbox_"+chatboxtitle).css('right',width+'px');}
chatBoxes.push(chatboxtitle);if(minimizeChatBox==1){minimizedChatBoxes=new Array();if($.cookie('chatbox_minimized')){minimizedChatBoxes=$.cookie('chatbox_minimized').split(/\|/);}
minimize=0;for(j=0;j<minimizedChatBoxes.length;j++){if(minimizedChatBoxes[j]==chatboxtitle){minimize=1;}}
if(minimize==1){$('#chatbox_'+chatboxtitle+' .chatboxcontent').css('display','none');$('#chatbox_'+chatboxtitle+' .chatboxinput').css('display','none');}}
chatboxFocus[chatboxtitle]=false;$("#chatbox_"+chatboxtitle+" .chatboxtextarea").blur(function(){chatboxFocus[chatboxtitle]=false;$("#chatbox_"+chatboxtitle+" .chatboxtextarea").removeClass('chatboxtextareaselected');}).focus(function(){chatboxFocus[chatboxtitle]=true;newMessages[chatboxtitle]=false;$('#chatbox_'+chatboxtitle+' .chatboxhead').removeClass('chatboxblink');$("#chatbox_"+chatboxtitle+" .chatboxtextarea").addClass('chatboxtextareaselected');});$("#chatbox_"+chatboxtitle).click(function(){if($('#chatbox_'+chatboxtitle+' .chatboxcontent').css('display')!='none'){$("#chatbox_"+chatboxtitle+" .chatboxtextarea").focus();}});$("#chatbox_"+chatboxtitle).show();}
window.chatHeartbeat=function(){var itemsfound=0;if(windowFocus==false){var blinkNumber=0;var titleChanged=0;for(x in newMessagesWin){if(newMessagesWin[x]==true){++blinkNumber;if(blinkNumber>=blinkOrder){document.title=x+' says...';titleChanged=1;break;}}}
if(titleChanged==0){document.title=originalTitle;blinkOrder=0;}else{++blinkOrder;}}else{for(x in newMessagesWin){newMessagesWin[x]=false;}}
for(x in newMessages){if(newMessages[x]==true){if(chatboxFocus[x]==false){$('#chatbox_'+x+' .chatboxhead').toggleClass('chatboxblink');}}}
$.ajax({url:"https://www.starfuckers.org/ajax/chat/bz",cache:false,dataType:"json",success:function(data){$.each(data.items,function(i,item){if(item){chatboxtitle=item.f;if($("#chatbox_"+chatboxtitle).length<=0){createChatBox(chatboxtitle);}
if($("#chatbox_"+chatboxtitle).css('display')=='none'){$("#chatbox_"+chatboxtitle).css('display','block');restructureChatBoxes();}
if(item.s==1){item.f=username;}
if(item.s==2){$("#chatbox_"+chatboxtitle+" .chatboxcontent").append('<div class="chatboxmessage"><span class="chatboxinfo">'+item.m+'</span></div>');}else{newMessages[chatboxtitle]=true;newMessagesWin[chatboxtitle]=true;$("#chatbox_"+chatboxtitle+" .chatboxcontent").append('<div class="chatboxmessage"><span class="chatboxmessagefrom">'+item.f+':&nbsp;&nbsp;</span><span class="chatboxmessagecontent">'+item.m+'</span></div>');}
$("#chatbox_"+chatboxtitle+" .chatboxcontent").scrollTop($("#chatbox_"+chatboxtitle+" .chatboxcontent")[0].scrollHeight);itemsfound+=1;}});chatHeartbeatCount++;if(itemsfound>0){chatHeartbeatTime=minChatHeartbeat;chatHeartbeatCount=1;}else if(chatHeartbeatCount>=10){chatHeartbeatTime*=2;chatHeartbeatCount=1;if(chatHeartbeatTime>maxChatHeartbeat){chatHeartbeatTime=maxChatHeartbeat;}}
setTimeout('chatHeartbeat();',chatHeartbeatTime);}});}
window.closeChatBox=function(chatboxtitle){$('#chatbox_'+chatboxtitle).css('display','none');restructureChatBoxes();$.post("https://www.starfuckers.org/ajax/chat/close/bz",{chatbox:chatboxtitle},function(data){});}
window.toggleChatBoxGrowth=function(chatboxtitle){if($('#chatbox_'+chatboxtitle+' .chatboxcontent').css('display')=='none'){var minimizedChatBoxes=new Array();if($.cookie('chatbox_minimized')){minimizedChatBoxes=$.cookie('chatbox_minimized').split(/\|/);}
var newCookie='';for(i=0;i<minimizedChatBoxes.length;i++){if(minimizedChatBoxes[i]!=chatboxtitle){newCookie+=chatboxtitle+'|';}}
newCookie=newCookie.slice(0,-1)
$.cookie('chatbox_minimized',newCookie);$('#chatbox_'+chatboxtitle+' .chatboxcontent').css('display','block');$('#chatbox_'+chatboxtitle+' .chatboxinput').css('display','block');$("#chatbox_"+chatboxtitle+" .chatboxcontent").scrollTop($("#chatbox_"+chatboxtitle+" .chatboxcontent")[0].scrollHeight);$('#title_'+chatboxtitle).attr('onclick',"goToProfile('"+chatboxtitle+"'); return false;").addClass('chatboxhover');}else{var newCookie=chatboxtitle;if($.cookie('chatbox_minimized')){newCookie+='|'+$.cookie('chatbox_minimized');}
$.cookie('chatbox_minimized',newCookie);$('#chatbox_'+chatboxtitle+' .chatboxcontent').css('display','none');$('#chatbox_'+chatboxtitle+' .chatboxinput').css('display','none');$('#title_'+chatboxtitle).removeAttr('onclick').removeClass('çhatboxhover');}}
window.checkChatBoxInputKey=function(event,chatboxtextarea,chatboxtitle){if(event.keyCode==13&&event.shiftKey==0){message=$(chatboxtextarea).val();message=message.replace(/^\s+|\s+$/g,"");$(chatboxtextarea).val('');$(chatboxtextarea).focus();$(chatboxtextarea).css('height','44px');if(message!=''){$.post("https://www.starfuckers.org/messaging/ajax/bz",{to:chatboxtitle,message:message},function(data){message=message.replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;");$("#chatbox_"+chatboxtitle+" .chatboxcontent").append('<div class="chatboxmessage"><span class="chatboxmessagefrom">'+username+':&nbsp;&nbsp;</span><span class="chatboxmessagecontent">'+message+'</span></div>');$("#chatbox_"+chatboxtitle+" .chatboxcontent").scrollTop($("#chatbox_"+chatboxtitle+" .chatboxcontent")[0].scrollHeight);});}
chatHeartbeatTime=minChatHeartbeat;chatHeartbeatCount=1;return false;}
var adjustedHeight=chatboxtextarea.clientHeight;var maxHeight=94;if(maxHeight>adjustedHeight){adjustedHeight=Math.max(chatboxtextarea.scrollHeight,adjustedHeight);if(maxHeight)
adjustedHeight=Math.min(maxHeight,adjustedHeight);if(adjustedHeight>chatboxtextarea.clientHeight)
$(chatboxtextarea).css('height',adjustedHeight+8+'px');}else{$(chatboxtextarea).css('overflow','auto');}}
window.startChatSession=function(){$.ajax({url:"https://www.starfuckers.org/messaging/open/ajax/bz",cache:false,dataType:"json",success:function(data){username=data.username;$.each(data.items,function(i,item){if(item){chatboxtitle=item.f;if($("#chatbox_"+chatboxtitle).length<=0){createChatBox(chatboxtitle,1);}
if(item.s==1){item.f=username;}
if(item.s==2){$("#chatbox_"+chatboxtitle+" .chatboxcontent").append('<div class="chatboxmessage"><span class="chatboxinfo">'+item.m+'</span></div>');}else{$("#chatbox_"+chatboxtitle+" .chatboxcontent").append('<div class="chatboxmessage"><span class="chatboxmessagefrom">'+item.f+':&nbsp;&nbsp;</span><span class="chatboxmessagecontent">'+item.m+'</span></div>');}}});for(i=0;i<chatBoxes.length;i++){chatboxtitle=chatBoxes[i];$("#chatbox_"+chatboxtitle+" .chatboxcontent").scrollTop($("#chatbox_"+chatboxtitle+" .chatboxcontent")[0].scrollHeight);setTimeout('$("#chatbox_"+chatboxtitle+" .chatboxcontent").scrollTop($("#chatbox_"+chatboxtitle+" .chatboxcontent")[0].scrollHeight);',100);}
setTimeout('chatHeartbeat();',chatHeartbeatTime);}});}
window.smE=function(){$.post('https://www.starfuckers.org/ajax/bz',function(a){if(a==0){}
else if(a!=0&&sf.chat_app.activity==0)
{sf.chat_app.activity=1;sf.app_init();};});}
$(document).ready(function(){originalTitle=document.title;startChatSession();$([window,document]).blur(function(){windowFocus=false;}).focus(function(){windowFocus=true;document.title=originalTitle;});prepareFarea();window.seon=setInterval(function(){prepareFarea();},1000);window.soen=setInterval(function(){doFriends();},60000);});